name: me
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.17
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets\images\instagram.png

  fonts:
    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf